### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nicole-ge** [nehalist/angular7-models#1] opened 2020-01-10 21:33 UTC
Hello,
I like this article. I tried to rebuild your example by start usin directly a json file. Sorry I'm a newbie and couldn't reproduce the Right json file to make your example works. can you please help me and post the example json file.

Kind regards

**Comment by nehalist** [comment] 2020-01-11 10:47
Could you provide more information on "couldn't reproduce the right json"? It would help a lot to your code too.

**Comment by nicole-ge** [comment] 2020-01-11 12:22
Hi,

I have download your code.

Then I have add a new file in the source: /app/assets/data.json

With the content in data.json: (json is valid by validator)
```
{ 
  "users": [
  {
    "firstName": "Jesse",
    "lastName": "Pinkman",
    "position": "Manufacturer",
    "cars": [
      {
        "brand": "BMW",
        "model": "M3",
        "kW": 338
      }
    ]
  },
  {
    "firstName": "Walter",
    "lastName": "White",
    "position": "CEO",
    "cars": [
      {
        "brand": "BMW",
        "model": "335i",
        "kW": 225
      },
      {
        "brand": "Lamborghini",
        "model": "Aventador",
        "kW": 566
      }
    ]
  }
]
}
```

Afterwards I changed the following part in your code:
/app/services/user.service.ts

```
import {User} from '../models/user.model';
import {catchError, map} from 'rxjs/operators';

@Injectable({
  providedIn: 'root'
})
export class UserService {

  constructor(private httpService: HttpClient) {
  }

  public getUser(id: number): Observable<User> {
    return this.httpService.get<User>(`../../assets/data.json/user/${id}`).pipe(
      map(data => new User().deserialize(data)),
      catchError(() => throwError('User not found'))
    );
  }

  public getAllUsers(): Observable<User[]> {
    return this.httpService.get<User[]>(`../../assets/data.json/users`).pipe(
      map(data => data.map(data => new User().deserialize(data)))
    );
  }
}

```

I have the app I couldn't access the data. What I'm doing wrong?

Kind regards

**Comment by hazeeq-dev** [comment] 2020-02-15 05:56
I'm probably having a similar problem as @nicole-ge after following your guide.
`fruits.service.ts:84 TypeError: data.map is not a function`
In your case you showed that you can get all users in your `getAllUsers` function in your service, but the error points to the `data.map` line within it. It is somehow not an array? My JSON response format is the same as @nicole-ge

**Comment by nehalist** [comment] 2020-02-15 10:49
I don't think that 

```
this.httpService.get<User>(`../../assets/data.json/user/${id}`)
```

works. Regarding the error message the response is not an array (hence there's no `.map` on it).

**Comment by hazeeq-dev** [comment] 2020-02-16 10:10
Yeah I know for sure that is wrong. Perhaps you can help me out for my question on stackoverflow? I have a sample of my response and code there.
[https://stackoverflow.com/questions/60232944/ionic-4-angular-data-map-is-not-a-function](https://stackoverflow.com/questions/60232944/ionic-4-angular-data-map-is-not-a-function)

**Comment by nehalist** [comment] 2020-02-16 10:37
This entire issue is a bit of its purpose, hence I'm closing it now. I'll try to help on SO.

**Closed as completed by nehalist** 2020-02-16 10:37 UTC
